package life.majiang.community.mapper;

import java.util.List;
import life.majiang.community.model.User;
import life.majiang.community.model.UserExample;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSER
     *
     * @mbg.generated Tue Jul 11 20:43:22 CST 2023
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSER
     *
     * @mbg.generated Tue Jul 11 20:43:22 CST 2023
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSER
     *
     * @mbg.generated Tue Jul 11 20:43:22 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSER
     *
     * @mbg.generated Tue Jul 11 20:43:22 CST 2023
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSER
     *
     * @mbg.generated Tue Jul 11 20:43:22 CST 2023
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSER
     *
     * @mbg.generated Tue Jul 11 20:43:22 CST 2023
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSER
     *
     * @mbg.generated Tue Jul 11 20:43:22 CST 2023
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSER
     *
     * @mbg.generated Tue Jul 11 20:43:22 CST 2023
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSER
     *
     * @mbg.generated Tue Jul 11 20:43:22 CST 2023
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSER
     *
     * @mbg.generated Tue Jul 11 20:43:22 CST 2023
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSER
     *
     * @mbg.generated Tue Jul 11 20:43:22 CST 2023
     */
    int updateByPrimaryKey(User record);
}