package life.majiang.community.mbg.mapper;

import java.util.List;
import life.majiang.community.mbg.model.User;
import life.majiang.community.mbg.model.UserExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_USER
     *
     * @mbg.generated Sun Dec 17 22:03:27 CST 2023
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_USER
     *
     * @mbg.generated Sun Dec 17 22:03:27 CST 2023
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_USER
     *
     * @mbg.generated Sun Dec 17 22:03:27 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_USER
     *
     * @mbg.generated Sun Dec 17 22:03:27 CST 2023
     */
    int insert(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_USER
     *
     * @mbg.generated Sun Dec 17 22:03:27 CST 2023
     */
    int insertSelective(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_USER
     *
     * @mbg.generated Sun Dec 17 22:03:27 CST 2023
     */
    List<User> selectByExampleWithRowbounds(UserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_USER
     *
     * @mbg.generated Sun Dec 17 22:03:27 CST 2023
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_USER
     *
     * @mbg.generated Sun Dec 17 22:03:27 CST 2023
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_USER
     *
     * @mbg.generated Sun Dec 17 22:03:27 CST 2023
     */
    int updateByExampleSelective(@Param("row") User row, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_USER
     *
     * @mbg.generated Sun Dec 17 22:03:27 CST 2023
     */
    int updateByExample(@Param("row") User row, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_USER
     *
     * @mbg.generated Sun Dec 17 22:03:27 CST 2023
     */
    int updateByPrimaryKeySelective(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_USER
     *
     * @mbg.generated Sun Dec 17 22:03:27 CST 2023
     */
    int updateByPrimaryKey(User row);
}