package life.majiang.community.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSER.ID
     *
     * @mbg.generated Wed Jul 26 15:37:04 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSER.ACCOUNT_ID
     *
     * @mbg.generated Wed Jul 26 15:37:04 CST 2023
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSER.NAME
     *
     * @mbg.generated Wed Jul 26 15:37:04 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSER.TOKEN
     *
     * @mbg.generated Wed Jul 26 15:37:04 CST 2023
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSER.GMT_CREATE
     *
     * @mbg.generated Wed Jul 26 15:37:04 CST 2023
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSER.GMT_MODIFIED
     *
     * @mbg.generated Wed Jul 26 15:37:04 CST 2023
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSER.BIO
     *
     * @mbg.generated Wed Jul 26 15:37:04 CST 2023
     */
    private String bio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSER.AVATAR_URL
     *
     * @mbg.generated Wed Jul 26 15:37:04 CST 2023
     */
    private String avatarUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSER.ID
     *
     * @return the value of CUSER.ID
     *
     * @mbg.generated Wed Jul 26 15:37:04 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSER.ID
     *
     * @param id the value for CUSER.ID
     *
     * @mbg.generated Wed Jul 26 15:37:04 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSER.ACCOUNT_ID
     *
     * @return the value of CUSER.ACCOUNT_ID
     *
     * @mbg.generated Wed Jul 26 15:37:04 CST 2023
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSER.ACCOUNT_ID
     *
     * @param accountId the value for CUSER.ACCOUNT_ID
     *
     * @mbg.generated Wed Jul 26 15:37:04 CST 2023
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSER.NAME
     *
     * @return the value of CUSER.NAME
     *
     * @mbg.generated Wed Jul 26 15:37:04 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSER.NAME
     *
     * @param name the value for CUSER.NAME
     *
     * @mbg.generated Wed Jul 26 15:37:04 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSER.TOKEN
     *
     * @return the value of CUSER.TOKEN
     *
     * @mbg.generated Wed Jul 26 15:37:04 CST 2023
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSER.TOKEN
     *
     * @param token the value for CUSER.TOKEN
     *
     * @mbg.generated Wed Jul 26 15:37:04 CST 2023
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSER.GMT_CREATE
     *
     * @return the value of CUSER.GMT_CREATE
     *
     * @mbg.generated Wed Jul 26 15:37:04 CST 2023
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSER.GMT_CREATE
     *
     * @param gmtCreate the value for CUSER.GMT_CREATE
     *
     * @mbg.generated Wed Jul 26 15:37:04 CST 2023
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSER.GMT_MODIFIED
     *
     * @return the value of CUSER.GMT_MODIFIED
     *
     * @mbg.generated Wed Jul 26 15:37:04 CST 2023
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSER.GMT_MODIFIED
     *
     * @param gmtModified the value for CUSER.GMT_MODIFIED
     *
     * @mbg.generated Wed Jul 26 15:37:04 CST 2023
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSER.BIO
     *
     * @return the value of CUSER.BIO
     *
     * @mbg.generated Wed Jul 26 15:37:04 CST 2023
     */
    public String getBio() {
        return bio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSER.BIO
     *
     * @param bio the value for CUSER.BIO
     *
     * @mbg.generated Wed Jul 26 15:37:04 CST 2023
     */
    public void setBio(String bio) {
        this.bio = bio == null ? null : bio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSER.AVATAR_URL
     *
     * @return the value of CUSER.AVATAR_URL
     *
     * @mbg.generated Wed Jul 26 15:37:04 CST 2023
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSER.AVATAR_URL
     *
     * @param avatarUrl the value for CUSER.AVATAR_URL
     *
     * @mbg.generated Wed Jul 26 15:37:04 CST 2023
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }
}