spring:
  kafka:
    bootstrap-servers:
    - localhost:9092
    template:
      default-topic: tacocloud.orders.topic
      
    producer:      
      acks: 1
      value-serializer: tacos.messaging.OrderSerializer
      
    consumer:
      bootstrap-servers:
      - localhost:9092
      auto-offset-reset: latest
      group-id: kafkaListener
      value-deserializer: tacos.messaging.OrderDeserializer
        